services:
  - type: web
    name: backend
    env: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    pullRequestPreviewsEnabled: true
